# 0.1. Importación de libreria y SQL

In [1]:
from sqlalchemy import create_engine
import sqlalchemy
import mysql.connector as mysql
import pandas as pd

# 0.2. Conexión a SQL

In [2]:
# Parámetros de conexión
user     = 'root'
password = 'MikaKota15MySQL'
db = 'NUCLIO'
sqlServer = 'localhost' # debería ser IP o DNS del servidor de la base de datos

# Creamos string de conexión
connStr = "mysql+mysqlconnector://" + user + ":" + password + "@" + sqlServer +  "/"  + db

# print de string de conexión
print (connStr)

# Conectamos con el servidor
conn = create_engine(connStr).connect()

mysql+mysqlconnector://root:MikaKota15MySQL@localhost/NUCLIO

# 0.3. Paso las tablas a DataFrame y las subimos a SQL

In [3]:
alojamiento=pd.read_excel("ALOJAMIENTO.xlsx")
alojamiento

,CODIGO_ALOJAMIENTO,NOMBRE,CANT_BANYOS,CANT_HAB,SALON,TERRAZA,AIREC_ACOND,PISCINA,SUPERFICIE
0,ALOJ001,Villa Sol del Mar,2,3,SI,SI,SI,SI,120
1,ALOJ002,Apartamento Las Palmeras,1,2,SI,NO,SI,NO,75
2,ALOJ003,Cabaña El Refugio,1,1,NO,SI,NO,NO,45
3,ALOJ004,Piso Centro Histórico,2,3,SI,SI,SI,NO,90
4,ALOJ005,Estudio Playa Blanca,1,1,NO,NO,SI,NO,40
5,ALOJ006,Chalet Vista al Lago,3,4,SI,SI,SI,SI,150
6,ALOJ007,Dúplex Jardines del Sur,2,3,SI,SI,SI,SI,130
7,ALOJ008,Loft Urbano,1,1,SI,NO,SI,NO,60
8,ALOJ009,Casa Rústica Montaña,2,2,SI,SI,NO,NO,85
9,ALOJ010,Ático del Sol,3,3,SI,SI,SI,NO,88
10,ALOJ011,Cabaña Bosque Encantado,1,2,NO,SI,NO,NO,65
11,ALOJ012,Villa Palmeras,2,3,SI,SI,SI,SI,110
12,ALOJ013,Apartamento Moderno,1,2,SI,NO,SI,NO,80
13,ALOJ014,Casa del Mar,3,4,SI,SI,SI,SI,160
14,ALOJ015,Dúplex Las Rocas,3,4,SI,SI,SI,NO,120
15,ALOJ016,Estudio Urbano,1,1,NO,NO,SI,NO,35
16,ALOJ017,Chalet Jardín Secreto,3,5,SI,SI,SI,SI,180
17,ALOJ018,Piso Parque Central,2,4,SI,SI,SI,NO,100
18,ALOJ019,Casa Río Claro,2,2,SI,SI,NO,NO,95
19,ALOJ020,Loft Estación Norte,1,1,SI,NO,SI,NO,55

In [5]:
alojamiento.to_sql('alojamiento', conn)

20

In [6]:
precio=pd.read_excel("PRECIO.xlsx")
precio

   CODIGO_ALOJAMIENTO  PRECIO_ALQUILER RESERVA  PORCENTAJE_RESERVA
0             ALOJ001             1800      SI                 100
1             ALOJ002              780      SI                  25
2             ALOJ003              800      NO                   0
3             ALOJ004             1600      SI                  25
4             ALOJ005              900      NO                   0
5             ALOJ006             1200      NO                   0
6             ALOJ007             1300      NO                   0
7             ALOJ008             1500      SI                  25
8             ALOJ009             1600      SI                 100
9             ALOJ010             1750      SI                  25
10            ALOJ011             1825      NO                   0
11            ALOJ012             1750      NO                   0
12            ALOJ013             1652      NO                   0
13            ALOJ014             1941      NO                   0
14            ALOJ015             1800      SI                  25
15            ALOJ016             2000      SI                  30
16            ALOJ017             2120      NO                   0
17            ALOJ018             1900      SI                  25
18            ALOJ019             1570      NO                   0
19            ALOJ020             1580      NO                   0

In [7]:
precio.to_sql('precio', conn)

20

In [8]:
puntuacion=pd.read_excel("PUNTUACION.xlsx")
puntuacion

   CODIGO_ALOJAMIENTO  PUNTOS            AGENCIA  PUNTOS_AGENCIA
0             ALOJ001     5.0         GlobalHome             4.4
1             ALOJ002     4.2         AndesRenta             4.1
2             ALOJ003     4.1       AlquilaFacil             4.0
3             ALOJ004     4.6         CaribeRent             4.6
4             ALOJ005     4.4           RentaTop             3.8
5             ALOJ006     4.3         TerraHouse             4.9
6             ALOJ007     4.9       SevillaRooms             4.5
7             ALOJ008     4.8          ChileVive             4.3
8             ALOJ009     4.7         MexicoRent             4.8
9             ALOJ010     4.8          UYAlquila             4.9
10            ALOJ011     4.0      MalagaTurismo             4.9
11            ALOJ012     4.2        CórdobaStay             4.6
12            ALOJ013     3.8         AndesElite             4.3
13            ALOJ014     4.7        BogotaLodge             4.5
14            ALOJ015     4.9  EasyStay Valencia             4.7
15            ALOJ016     4.3    PuntaAlquileres             4.4
16            ALOJ017     4.9         CuscoRenta             4.4
17            ALOJ018     4.7       MendozaRooms             4.7
18            ALOJ019     4.9            GDLRent             4.2
19            ALOJ020     4.9           VivaStay             4.9

In [10]:
puntuacion.to_sql('puntuacion', conn)

20

In [11]:
ubicacion=pd.read_excel("UBICACION.xlsx")
ubicacion

   CODIGO_ALOJAMIENTO      PAIS     CIUDAD  DIST_METRO  DIST_CENTRO
0             ALOJ001  Portugal      Liboa         1.0          2.0
1             ALOJ002    España     Madrid         0.5          0.8
2             ALOJ003    España  Barcelona         0.9          0.4
3             ALOJ004   Francia   Marsella         3.0          4.0
4             ALOJ005  Portugal     Oporto         4.0          3.0
5             ALOJ006   Francia      Paris         2.0          2.0
6             ALOJ007   Francia   Toulouse         1.0          3.0
7             ALOJ008    España  Barcelona         2.0          3.0
8             ALOJ009    España     Madrid         2.0          4.0
9             ALOJ010    España     Bilbao         2.0          5.0
10            ALOJ011    Italia      Milan         0.5          0.7
11            ALOJ012    Italia       Roma         1.0          0.8
12            ALOJ013    España    Sevilla         2.0          0.9
13            ALOJ014    Italia   Cerdegna         0.9          4.0
14            ALOJ015    España     Málaga         2.0          4.0
15            ALOJ016    Italia       Roma         2.0          2.0
16            ALOJ017   Francia      Paris         1.0          2.0
17            ALOJ018    España      Ibiza         2.0          4.0
18            ALOJ019  Portugal      Lagos         2.0          2.0
19            ALOJ020  Portugal    Madeira         3.0          2.0

In [13]:
ubicacion.to_sql('ubicacion', conn)

20

# 1.0. QUERIES

### 1.1. El cliente exige terraza y aire acondicionado, pero no quiere piscina.

In [3]:

sSQL = """

SELECT CODIGO_ALOJAMIENTO
FROM ALOJAMIENTO
WHERE TERRAZA='SI' AND AIREC_ACOND='SI' AND PISCINA='NO'

"""
pd.read_sql(sSQL, conn)

  CODIGO_ALOJAMIENTO
0            ALOJ004
1            ALOJ010
2            ALOJ015
3            ALOJ018

### 1.2. No se alojará en estudios que no tengan salón ni en propiedades con solo un baño

In [4]:
sSQL = """

SELECT CODIGO_ALOJAMIENTO
FROM ALOJAMIENTO
WHERE SALON='SI' AND CANT_BANYOS>1

"""
pd.read_sql(sSQL, conn)

   CODIGO_ALOJAMIENTO
0             ALOJ001
1             ALOJ004
2             ALOJ006
3             ALOJ007
4             ALOJ009
5             ALOJ010
6             ALOJ012
7             ALOJ014
8             ALOJ015
9             ALOJ017
10            ALOJ018
11            ALOJ019

### 1.3.  La propiedad debe tener como mínimo 80m2

In [5]:
sSQL = """

SELECT CODIGO_ALOJAMIENTO
FROM ALOJAMIENTO
WHERE SUPERFICIE>=80

"""
pd.read_sql(sSQL, conn)

   CODIGO_ALOJAMIENTO
0             ALOJ001
1             ALOJ004
2             ALOJ006
3             ALOJ007
4             ALOJ009
5             ALOJ010
6             ALOJ012
7             ALOJ013
8             ALOJ014
9             ALOJ015
10            ALOJ017
11            ALOJ018
12            ALOJ019

### 1.4. Como el cliente odia el ruido, no quiere alojarse en propiedades a menos de 1 km de una estación de metro ni a menos de 2 km del centro.

In [6]:
sSQL = """

SELECT CODIGO_ALOJAMIENTO
FROM UBICACION
WHERE DIST_METRO>1.0 AND DIST_CENTRO>2.0

"""
pd.read_sql(sSQL, conn)

  CODIGO_ALOJAMIENTO
0            ALOJ004
1            ALOJ005
2            ALOJ008
3            ALOJ009
4            ALOJ010
5            ALOJ015
6            ALOJ018

### 1.5. El rango permitido por el cliente para pagar es entre 1.500€ y 2.000€ la noche.

In [7]:
sSQL = """

SELECT CODIGO_ALOJAMIENTO
FROM PRECIO
WHERE PRECIO_ALQUILER BETWEEN 1500 AND 2000

"""
pd.read_sql(sSQL, conn)

   CODIGO_ALOJAMIENTO
0             ALOJ001
1             ALOJ004
2             ALOJ008
3             ALOJ009
4             ALOJ010
5             ALOJ011
6             ALOJ012
7             ALOJ013
8             ALOJ014
9             ALOJ015
10            ALOJ016
11            ALOJ018
12            ALOJ019
13            ALOJ020

### 1.6. Como en anteriores ocasiones ha tenido problemas de intentos de estafas con otras agencias, el cliente pide que el % de reserva no sea muy alto, pero tampoco tan bajo (porque le genera inseguridad) por lo que propone un 25%

In [8]:
sSQL = """

SELECT CODIGO_ALOJAMIENTO
FROM PRECIO
WHERE PORCENTAJE_RESERVA>=25

"""
pd.read_sql(sSQL, conn)

  CODIGO_ALOJAMIENTO
0            ALOJ001
1            ALOJ002
2            ALOJ004
3            ALOJ008
4            ALOJ009
5            ALOJ010
6            ALOJ015
7            ALOJ016
8            ALOJ018

In [9]:
sSQL = """

SELECT CODIGO_ALOJAMIENTO
FROM PRECIO
WHERE PORCENTAJE_RESERVA=25

"""
pd.read_sql(sSQL, conn)

  CODIGO_ALOJAMIENTO
0            ALOJ002
1            ALOJ004
2            ALOJ008
3            ALOJ010
4            ALOJ015
5            ALOJ018

### 1.7. Quiere que el alojamiento tenga más de 4,5 puntos de confianza y que la agencia que lo lleva tenga más de 4 puntos

In [10]:
sSQL = """

SELECT CODIGO_ALOJAMIENTO
FROM PUNTUACION
WHERE PUNTOS>4.5 AND PUNTOS_AGENCIA>4

"""
pd.read_sql(sSQL, conn)

   CODIGO_ALOJAMIENTO
0             ALOJ001
1             ALOJ004
2             ALOJ007
3             ALOJ008
4             ALOJ009
5             ALOJ010
6             ALOJ014
7             ALOJ015
8             ALOJ017
9             ALOJ018
10            ALOJ019
11            ALOJ020

### 1.8. Crear en una única query la combinación de los filtros anteriores parahallar las propiedades que finalmente cumplen con todas las exigencias del cliente.

In [11]:
sSQL = """

SELECT *
FROM ALOJAMIENTO A
JOIN PRECIO B ON A.CODIGO_ALOJAMIENTO=B.CODIGO_ALOJAMIENTO
JOIN PUNTUACION C ON A.CODIGO_ALOJAMIENTO=C.CODIGO_ALOJAMIENTO
JOIN UBICACION D ON A.CODIGO_ALOJAMIENTO=D.CODIGO_ALOJAMIENTO
WHERE
    TERRAZA='SI' 
    AND AIREC_ACOND='SI' 
    AND PISCINA='NO' 
    AND SALON='SI' 
    AND CANT_BANYOS>1
    AND SUPERFICIE>=80
    AND DIST_METRO>1.0 AND DIST_CENTRO>2.0
    AND PRECIO_ALQUILER BETWEEN 1500 AND 2000
    AND PORCENTAJE_RESERVA=25
    AND PUNTOS>4.5 AND PUNTOS_AGENCIA>4

"""
pd.read_sql(sSQL, conn)

,index,CODIGO_ALOJAMIENTO,NOMBRE,CANT_BANYOS,CANT_HAB,SALON,TERRAZA,AIREC_ACOND,PISCINA,SUPERFICIE,...,CODIGO_ALOJAMIENTO,PUNTOS,AGENCIA,PUNTOS_AGENCIA,index,CODIGO_ALOJAMIENTO,PAIS,CIUDAD,DIST_METRO,DIST_CENTRO
0,3,ALOJ004,Piso Centro Histórico,2,3,SI,SI,SI,NO,90,...,ALOJ004,4.6,CaribeRent,4.6,3,ALOJ004,Francia,Marsella,3.0,4.0
1,9,ALOJ010,Ático del Sol,3,3,SI,SI,SI,NO,88,...,ALOJ010,4.8,UYAlquila,4.9,9,ALOJ010,España,Bilbao,2.0,5.0
2,14,ALOJ015,Dúplex Las Rocas,3,4,SI,SI,SI,NO,120,...,ALOJ015,4.9,EasyStay Valencia,4.7,14,ALOJ015,España,Málaga,2.0,4.0
3,17,ALOJ018,Piso Parque Central,2,4,SI,SI,SI,NO,100,...,ALOJ018,4.7,MendozaRooms,4.7,17,ALOJ018,España,Ibiza,2.0,4.0

### 1.9. ¿Cuál de estos 4 alojamientos le recomendarías y por qué? 

Aunque hay cuatro alojamientos que cumplen todos los requisitos técnicos del cliente, es importante tener en cuenta otros factores relacionados con su perfil y el contexto del viaje que quiere hacer. El cliente es un cantante famoso que quiere pasar unos días de descanso con su familia antes de iniciar una gira de conciertos, por lo que la tranquilidad, la privacidad y el entorno son aspectos clave, además de que el destino sea de playa.

En primer lugar, descartaría el alojamiento de Bilbao, ya que en la ciudad no hay playa y nuestro cliente tendría que desplazarse hasta la costa durante una hora aproximádamente. Además, al encontrarse en el norte de España, el clima es más inestable incluso en verano, lo que podría dificultar el disfrutar de la playa, una de las exigencias principales.

También descaro el alojamiento de Marsella, principalmente por un tema de espacio. Este alojamiento cuenta con una superficie menorm, menos habitaciones y menos baños que las otras opciones, lo que lo hace menos adecuado para un grupo de ocho personas, donde es importante disponer de una buena distribución y comodidad.

Entre las dos opciones que quedan, Málaga e Ibiza, optaría por Málaga. Aunque ambos destinos son atractivos, Ibiza es un lugar con un alto foco mediático y una vida social muy intensa, lo que podría afectar a la privacidad del cliente. Málaga, en cambio, ofrece un entorno más tranquilo y familiar. Además, el alojamiento de Málaga destaca por ser el que mayor superficie y baños tiene, lo que mejora el confort del grupo.

Por lo tanto, recomiendaría el alojamiento Duplex Las Rocas de Málaga como la opción más adecuada para el cliente y su familia.

# 2.0 QUERIES PARTE II

### 2.1. ¿Cuál es la suma total de metros cuadrados de los alojamientos que tienen piscina?

In [13]:
sSQL = """
SELECT SUM(SUPERFICIE) AS SUPERFICIE_TOTAL_CON_PISCINA
FROM ALOJAMIENTO
WHERE PISCINA = 'SI'
"""
pd.read_sql(sSQL, conn)

   SUPERFICIE_TOTAL_CON_PISCINA
0                         850.0

### 2.2. ¿Cuál es el alojamiento con mayor superficie?

In [14]:
sSQL = """
SELECT CODIGO_ALOJAMIENTO, NOMBRE, SUPERFICIE
FROM ALOJAMIENTO
ORDER BY SUPERFICIE DESC
LIMIT 1
"""
pd.read_sql(sSQL, conn)

  CODIGO_ALOJAMIENTO                 NOMBRE  SUPERFICIE
0            ALOJ017  Chalet Jardín Secreto         180

### 2.3. ¿Cuál es el alojamiento con menor superficie?

In [15]:
sSQL = """
SELECT CODIGO_ALOJAMIENTO, NOMBRE, SUPERFICIE
FROM ALOJAMIENTO
ORDER BY SUPERFICIE ASC
LIMIT 1
"""
pd.read_sql(sSQL, conn)

  CODIGO_ALOJAMIENTO          NOMBRE  SUPERFICIE
0            ALOJ016  Estudio Urbano          35

### 2.4. ¿Cuántos alojamientos tienen salón?

In [16]:
sSQL = """
SELECT COUNT(SALON) AS ALOJAMIENTOS_CON_SALON
FROM ALOJAMIENTO
WHERE SALON = 'SI'
"""
pd.read_sql(sSQL, conn)

   ALOJAMIENTOS_CON_SALON
0                      16

### 2.5. ¿Cuántos alojamientos tienen terraza?

In [17]:
sSQL = """
SELECT COUNT(TERRAZA) AS ALOJAMIENTOS_CON_TERRAZA
FROM ALOJAMIENTO
WHERE TERRAZA = 'SI'
"""
pd.read_sql(sSQL, conn)

   ALOJAMIENTOS_CON_TERRAZA
0                        14

### 2.6. ¿Cuántos alojamientos hay por cada país según nuestra tabla de UBICACIÓN?

In [18]:
sSQL = """
SELECT PAIS, COUNT(CODIGO_ALOJAMIENTO) AS ALOJAMIENTOS_POR_PAIS
FROM UBICACION
GROUP BY PAIS
ORDER BY ALOJAMIENTOS_POR_PAIS DESC
"""
pd.read_sql(sSQL, conn)

       PAIS  ALOJAMIENTOS_POR_PAIS
0    España                      8
1  Portugal                      4
2   Francia                      4
3    Italia                      4

### 2.7. ¿Cuál es el promedio de precios de alquiler de todos los alojamientos según la tabla PRECIO?

In [19]:
sSQL = """
SELECT AVG(PRECIO_ALQUILER) AS PROMEDIO_PRECIO_ALQUILER
FROM PRECIO
"""
pd.read_sql(sSQL, conn)

   PROMEDIO_PRECIO_ALQUILER
0                    1568.4

### 2.8. ¿Cuáles son las 3 agencias que tienen la mayor puntuación de agencia (campo a usar: PUNTOS_AGENCIA) según la tabla PUNTUACION?

In [22]:
sSQL = """
SELECT AGENCIA, PUNTOS_AGENCIA AS TOP_3_AGENCIAS
FROM PUNTUACION
ORDER BY PUNTOS_AGENCIA DESC
LIMIT 3
"""
pd.read_sql(sSQL, conn)

         AGENCIA  TOP_3_AGENCIAS
0     TerraHouse             4.9
1      UYAlquila             4.9
2  MalagaTurismo             4.9

### 2.9. Muestra los alojamientos (código y nombre) que: Contengan la palabra ‘Piso’ en su nombre o que tengan piscina y aire acondicionado, pero no pasen los 150 metros de superficie o que tengan más de un baño

In [29]:
sSQL = """
SELECT CODIGO_ALOJAMIENTO, NOMBRE
FROM ALOJAMIENTO
WHERE NOMBRE LIKE '%PISO%'
OR ((AIREC_ACOND='SI' AND PISCINA='SI') AND (SUPERFICIE<=150 OR CANT_BANYOS>1))
"""
pd.read_sql(sSQL, conn)

  CODIGO_ALOJAMIENTO                   NOMBRE
0            ALOJ001        Villa Sol del Mar
1            ALOJ004    Piso Centro Histórico
2            ALOJ006     Chalet Vista al Lago
3            ALOJ007  Dúplex Jardines del Sur
4            ALOJ012           Villa Palmeras
5            ALOJ014             Casa del Mar
6            ALOJ017    Chalet Jardín Secreto
7            ALOJ018      Piso Parque Central

### 2.10. Muestra una consulta que muestre el código de alojamiento, el nombre, el precio y una columna donde veamos el precio del alquiler con el símbolo del euro al final de cada importe, esta nueva columna se debe llama PRECIO_MODIF

In [36]:
sSQL = """

SELECT A.CODIGO_ALOJAMIENTO, NOMBRE, PRECIO_ALQUILER, CONCAT(PRECIO_ALQUILER, ' €') AS PRECIO_MODIF
FROM ALOJAMIENTO A
JOIN PRECIO B ON A.CODIGO_ALOJAMIENTO=B.CODIGO_ALOJAMIENTO
"""
pd.read_sql(sSQL, conn)

   CODIGO_ALOJAMIENTO                    NOMBRE  PRECIO_ALQUILER PRECIO_MODIF
0             ALOJ001         Villa Sol del Mar             1800       1800 €
1             ALOJ002  Apartamento Las Palmeras              780        780 €
2             ALOJ003         Cabaña El Refugio              800        800 €
3             ALOJ004     Piso Centro Histórico             1600       1600 €
4             ALOJ005      Estudio Playa Blanca              900        900 €
5             ALOJ006      Chalet Vista al Lago             1200       1200 €
6             ALOJ007   Dúplex Jardines del Sur             1300       1300 €
7             ALOJ008               Loft Urbano             1500       1500 €
8             ALOJ009      Casa Rústica Montaña             1600       1600 €
9             ALOJ010             Ático del Sol             1750       1750 €
10            ALOJ011   Cabaña Bosque Encantado             1825       1825 €
11            ALOJ012            Villa Palmeras             1750       1750 €
12            ALOJ013       Apartamento Moderno             1652       1652 €
13            ALOJ014              Casa del Mar             1941       1941 €
14            ALOJ015          Dúplex Las Rocas             1800       1800 €
15            ALOJ016            Estudio Urbano             2000       2000 €
16            ALOJ017     Chalet Jardín Secreto             2120       2120 €
17            ALOJ018       Piso Parque Central             1900       1900 €
18            ALOJ019            Casa Río Claro             1570       1570 €
19            ALOJ020       Loft Estación Norte             1580       1580 €

### 2.11. Muestra una columna sobre la tabla PRECIO que se llame CATEGORIA_PRECIO y que indique la palabra ‘Bajo’ si el precio está entre 780 y 1000, ‘Medio’ si el precio está entre 1000 y 1700 y ‘Alto’ si es mayor a 1700

In [40]:
sSQL = """

SELECT CODIGO_ALOJAMIENTO, PRECIO_ALQUILER,
CASE
    WHEN PRECIO_ALQUILER BETWEEN 780 AND 1000 THEN 'Bajo'
    WHEN PRECIO_ALQUILER BETWEEN 1000 AND 1700 THEN 'Medio'
    WHEN PRECIO_ALQUILER > 1700 THEN 'Alto'
END AS CATEGORIA_PRECIO
FROM PRECIO
"""
pd.read_sql(sSQL, conn)

   CODIGO_ALOJAMIENTO  PRECIO_ALQUILER CATEGORIA_PRECIO
0             ALOJ001             1800             Alto
1             ALOJ002              780             Bajo
2             ALOJ003              800             Bajo
3             ALOJ004             1600            Medio
4             ALOJ005              900             Bajo
5             ALOJ006             1200            Medio
6             ALOJ007             1300            Medio
7             ALOJ008             1500            Medio
8             ALOJ009             1600            Medio
9             ALOJ010             1750             Alto
10            ALOJ011             1825             Alto
11            ALOJ012             1750             Alto
12            ALOJ013             1652            Medio
13            ALOJ014             1941             Alto
14            ALOJ015             1800             Alto
15            ALOJ016             2000             Alto
16            ALOJ017             2120             Alto
17            ALOJ018             1900             Alto
18            ALOJ019             1570            Medio
19            ALOJ020             1580            Medio

### Fin del entregable by Mika <3